# ============================================================
# PayGuard AI
# Dashboard
# Part 1 - Imports, Theme, Configuration & Data Loading
# ============================================================

import pandas as pd
import streamlit as st

from pathlib import Path

from components.theme import apply_theme

# ------------------------------------------------------------
# Apply Theme
# ------------------------------------------------------------

apply_theme()

# ------------------------------------------------------------
# Color Palette
# ------------------------------------------------------------

PRIMARY_COLOR = "#3B82F6"
SECONDARY_COLOR = "#8B5CF6"
SUCCESS_COLOR = "#10B981"
WARNING_COLOR = "#F59E0B"
DANGER_COLOR = "#EF4444"

# ------------------------------------------------------------
# Project Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"

SIMULATION_CSV = DATA_DIR / "simulations.csv"

# ------------------------------------------------------------
# Load Simulation History
# ------------------------------------------------------------

@st.cache_data(ttl=5)
def load_simulation_history():

    if not SIMULATION_CSV.exists():

        return pd.DataFrame()

    return pd.read_csv(SIMULATION_CSV)


history = load_simulation_history()
history = history.copy()

# ------------------------------------------------------------
# Page Header
# ------------------------------------------------------------

st.markdown(
    """
<div class="glass-card">

<h1 style="text-align:center;color:white;">
📊 PayGuard AI Dashboard
</h1>

<p style="text-align:center;color:#CBD5E1;font-size:18px;">
Real-time overview of fraud predictions generated by the
Machine Learning model.
</p>

</div>
""",
    unsafe_allow_html=True,
)

st.write("")
st.write("")
# ============================================================
# PART 2
# Dashboard Statistics
# ============================================================

if history.empty:

    total_predictions = 0
    fraud_count = 0
    suspicious_count = 0
    legitimate_count = 0
    fraud_rate = 0.0

else:

    total_predictions = len(history)

    fraud_count = len(
        history[history["risk"] == "Fraud"]
    )

    suspicious_count = len(
        history[history["risk"] == "Suspicious"]
    )

    legitimate_count = len(
        history[history["risk"] == "Legitimate"]
    )

    fraud_rate = (
        fraud_count / total_predictions
    ) * 100
# ============================================================
# PART 3
# KPI Cards
# ============================================================

st.subheader("📈 Dashboard Overview")

col1, col2, col3, col4, col5 = st.columns(5)

with col1:

    st.metric(
        "Total Predictions",
        total_predictions,
    )

with col2:

    st.metric(
        "Fraud",
        fraud_count,
    )

with col3:

    st.metric(
        "Suspicious",
        suspicious_count,
    )

with col4:

    st.metric(
        "Legitimate",
        legitimate_count,
    )

with col5:

    st.metric(
        "Fraud Rate",
        f"{fraud_rate:.1f}%",
    )

st.write("")
# ============================================================
# PART 4
# Risk Distribution Charts
# ============================================================

st.subheader("📊 Risk Distribution")

chart_col1, chart_col2 = st.columns(2)

risk_counts = pd.DataFrame(
    {
        "Risk": [
            "Fraud",
            "Suspicious",
            "Legitimate",
        ],
        "Count": [
            fraud_count,
            suspicious_count,
            legitimate_count,
        ],
    }
)

# ------------------------------------------------------------
# Pie Chart
# ------------------------------------------------------------

with chart_col1:

    st.markdown("#### 🥧 Distribution")

    st.plotly_chart(
        {
            "data": [
                {
                    "labels": risk_counts["Risk"],
                    "values": risk_counts["Count"],
                    "type": "pie",
                    "hole": 0.45,
                }
            ],
            "layout": {
                "height": 420,
                "margin": dict(l=20, r=20, t=20, b=20),
            },
        },
        width="stretch",
    )

# ------------------------------------------------------------
# Bar Chart
# ------------------------------------------------------------

with chart_col2:

    st.markdown("#### 📈 Risk Counts")

    st.bar_chart(
        risk_counts.set_index("Risk")
    )

st.write("")
# ============================================================
# PART 5
# Recent Predictions
# ============================================================

st.write("")
st.write("")

st.subheader("🧾 Recent Predictions")

display_columns = [
    "amount",
    "city",
    "merchant_category",
    "payment_method",
    "risk",
    "timestamp",
]

available_columns = [
    column
    for column in display_columns
    if column in history.columns
]

if available_columns:

    recent = (
        history[available_columns]
        .tail(10)
        .iloc[::-1]
    )

    rename_columns = {
        "amount": "Amount (₹)",
        "city": "City",
        "merchant_category": "Merchant",
        "payment_method": "Payment",
        "risk": "Prediction",
        "timestamp": "Time",
    }

    recent = recent.rename(columns=rename_columns)

    st.dataframe(
        recent,
        width="stretch",
        hide_index=True,
    )

else:

    st.info("No prediction history available.")