# ============================================================
# PayGuard AI
# Reports
# Part 1
# ============================================================

from pathlib import Path

import pandas as pd
import streamlit as st
import plotly.express as px

from components.theme import apply_theme

# ------------------------------------------------------------
# Apply Theme
# ------------------------------------------------------------

apply_theme()

# ------------------------------------------------------------
# Project Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"

SIMULATION_CSV = DATA_DIR / "simulations.csv"

# ------------------------------------------------------------
# Load Prediction History
# ------------------------------------------------------------

if SIMULATION_CSV.exists():

    history = pd.read_csv(SIMULATION_CSV)

else:

    history = pd.DataFrame()

# ------------------------------------------------------------
# Page Header
# ------------------------------------------------------------

st.markdown(
    """
<div class="glass-card">

<h1 style="text-align:center;">
📄 PayGuard AI Reports
</h1>

<p style="text-align:center;color:#CBD5E1;font-size:18px;">
Explore prediction trends, fraud analytics and transaction insights generated by the Machine Learning model.
</p>

</div>
""",
    unsafe_allow_html=True,
)

st.write("")
st.write("")
# ============================================================
# PART 2
# Prediction Trend
# ============================================================

st.subheader("📈 Prediction Trend")

if history.empty:

    st.info("No prediction history available.")

else:

    trend_data = history.copy()

    if "timestamp" in trend_data.columns:

        trend_data["timestamp"] = pd.to_datetime(
            trend_data["timestamp"],
            errors="coerce",
        )

        trend_data = trend_data.sort_values(
            "timestamp"
        )

        trend_data["Prediction Number"] = range(
            1,
            len(trend_data) + 1,
        )

        fig = px.line(

            trend_data,

            x="timestamp",

            y="Prediction Number",

            markers=True,

            title="Predictions Over Time",

        )

        fig.update_layout(

            height=450,

            xaxis_title="Time",

            yaxis_title="Total Predictions",

            template="plotly_dark",

        )

        st.plotly_chart(

            fig,

            width="stretch",

        )

    else:

        st.warning(
            "Timestamp column not found."
        )

st.write("")
st.write("")
# ============================================================
# PART 3
# Merchant Category Analysis
# ============================================================

st.subheader("🏪 Merchant Category Analysis")

if history.empty:

    st.info("No data available.")

else:

    col1, col2 = st.columns(2)

    # --------------------------------------------------------
    # Merchant Category Count
    # --------------------------------------------------------

    with col1:

        merchant_counts = (
            history["merchant_category"]
            .value_counts()
            .reset_index()
        )

        merchant_counts.columns = [
            "Merchant Category",
            "Transactions",
        ]

        fig = px.bar(

            merchant_counts,

            x="Merchant Category",

            y="Transactions",

            color="Transactions",

            title="Transactions by Merchant Category",

            text="Transactions",

        )

        fig.update_layout(

            template="plotly_dark",

            height=450,

            showlegend=False,

        )

        st.plotly_chart(
            fig,
            width="stretch",
        )

    # --------------------------------------------------------
    # Amount Distribution
    # --------------------------------------------------------

    with col2:

        fig = px.box(

            history,

            x="merchant_category",

            y="amount",

            color="merchant_category",

            title="Transaction Amount Distribution",

            points="all",

        )

        fig.update_layout(

            template="plotly_dark",

            height=450,

            showlegend=False,

        )

        st.plotly_chart(

            fig,

            width="stretch",

        )

st.write("")
st.write("")
# ============================================================
# PART 4
# Fraud Probability Analysis
# ============================================================

st.subheader("🎯 Fraud Probability Analysis")

if history.empty:

    st.info("No prediction history available.")

else:

    scatter_data = history.copy()

    scatter_data["Transaction"] = range(
        1,
        len(scatter_data) + 1,
    )

    fig = px.scatter(

        scatter_data,

        x="Transaction",

        y="prob_fraud",

        color="risk",

        size="amount",

        hover_data=[
            "merchant_category",
            "city",
            "payment_method",
        ],

        title="Fraud Probability by Transaction",

    )

    fig.update_layout(

        template="plotly_dark",

        height=520,

        xaxis_title="Transaction Number",

        yaxis_title="Fraud Probability",

    )

    st.plotly_chart(

        fig,

        width="stretch",

    )

st.write("")
st.write("")
# ============================================================
# PART 5
# Payment Method & Device Analysis
# ============================================================

st.subheader("💳 Payment & Device Analysis")

if history.empty:

    st.info("No prediction history available.")

else:

    col1, col2 = st.columns(2)

    # --------------------------------------------------------
    # Payment Method Distribution
    # --------------------------------------------------------

    with col1:

        payment_counts = (
            history["payment_method"]
            .value_counts()
            .reset_index()
        )

        payment_counts.columns = [
            "Payment Method",
            "Transactions",
        ]

        fig = px.pie(

            payment_counts,

            names="Payment Method",

            values="Transactions",

            hole=0.55,

            title="Payment Method Distribution",

        )

        fig.update_layout(

            template="plotly_dark",

            height=450,

        )

        st.plotly_chart(

            fig,

            width="stretch",

        )

    # --------------------------------------------------------
    # Device Distribution
    # --------------------------------------------------------

    with col2:

        device_counts = (
            history["device"]
            .value_counts()
            .reset_index()
        )

        device_counts.columns = [
            "Device",
            "Transactions",
        ]

        fig = px.bar(

            device_counts,

            x="Transactions",

            y="Device",

            orientation="h",

            color="Transactions",

            text="Transactions",

            title="Device Distribution",

        )

        fig.update_layout(

            template="plotly_dark",

            height=450,

            showlegend=False,

            yaxis_title="",

        )

        st.plotly_chart(

            fig,

            width="stretch",

        )

st.write("")
st.write("")
# ============================================================
# PART 6
# Detailed Prediction Report
# ============================================================

st.subheader("📋 Detailed Prediction Report")

if history.empty:

    st.info("No prediction history available.")

else:

    search = st.text_input(
        "🔍 Search by City, Merchant, Payment Method or Prediction"
    )

    report_df = history.copy()

    if search:

        search = search.lower()

        report_df = report_df[
            report_df.astype(str)
            .apply(
                lambda row: row.str.lower().str.contains(search)
            )
            .any(axis=1)
        ]

    columns = [

        "timestamp",

        "amount",

        "city",

        "merchant_category",

        "payment_method",

        "device",

        "risk",

        "prob_fraud",

        "prob_legit",

    ]

    columns = [
        c
        for c in columns
        if c in report_df.columns
    ]

    st.dataframe(

        report_df[columns],

        width="stretch",

        hide_index=True,

    )

st.write("")
st.write("")
# ============================================================
# PART 7
# Export Report
# ============================================================

st.subheader("📥 Export Report")

if history.empty:

    st.info("No report available.")

else:

    csv = history.to_csv(
        index=False
    ).encode("utf-8")

    st.download_button(

        label="⬇ Download Report (CSV)",

        data=csv,

        file_name="PayGuard_AI_Report.csv",

        mime="text/csv",

        width="stretch",

    )

st.write("")
st.write("")
# ============================================================
# PART 8
# Report Information
# ============================================================

st.subheader("ℹ️ Report Information")

if history.empty:

    st.warning("No report information available.")

else:

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Total Records",
            len(history),
        )

    with col2:

        latest = history.iloc[-1]["timestamp"]

        st.metric(
            "Last Updated",
            latest,
        )

st.write("")
st.divider()

st.caption(
    "© 2026 PayGuard AI • Fraud Analytics Report"
)