# ============================================================
# PayGuard AI
# Search
# Part 1 - Imports, Theme, Configuration & Data Loading
# ============================================================

from pathlib import Path

import pandas as pd
import streamlit as st

from components.theme import apply_theme

# ------------------------------------------------------------
# Apply Theme
# ------------------------------------------------------------

apply_theme()

# ------------------------------------------------------------
# Project Paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"

SIMULATION_CSV = DATA_DIR / "simulations.csv"

# ------------------------------------------------------------
# Load Simulation History
# ------------------------------------------------------------

@st.cache_data
def load_search_data():

    if SIMULATION_CSV.exists():

        return pd.read_csv(SIMULATION_CSV)

    return pd.DataFrame()

history = load_search_data()

# ------------------------------------------------------------
# Page Header
# ------------------------------------------------------------

st.markdown(
    """
<div class="glass-card">

<h1 style="text-align:center;">
🔍 PayGuard AI Search
</h1>

<p style="text-align:center;color:#CBD5E1;font-size:18px;">
Search, filter and investigate fraud prediction history generated by the Machine Learning model.
</p>

</div>
""",
    unsafe_allow_html=True,
)

st.write("")
st.write("")
# ============================================================
# PART 2
# Global Search
# ============================================================

st.subheader("🔍 Global Search")

search_query = st.text_input(

    "Search transactions",

    placeholder="Example: Fraud, Chennai, Grocery, UPI...",

)

filtered_history = history.copy()

if search_query and not history.empty:

    filtered_history = history[
        history.astype(str)
        .apply(
            lambda row: row.str.contains(
                search_query,
                case=False,
                na=False,
            )
        )
        .any(axis=1)
    ]

st.write("")
st.write("")
# ============================================================
# PART 3
# Advanced Filters
# ============================================================

st.subheader("🎛️ Advanced Filters")

if filtered_history.empty:

    st.info("No transactions available.")

else:

    col1, col2 = st.columns(2)

    with col1:

        risk_filter = st.selectbox(

            "Risk Level",

            ["All"] + sorted(
                filtered_history["risk"].dropna().unique().tolist()
            ),

        )

        city_filter = st.selectbox(

            "City",

            ["All"] + sorted(
                filtered_history["city"].dropna().unique().tolist()
            ),

        )

    with col2:

        merchant_filter = st.selectbox(

            "Merchant Category",

            ["All"] + sorted(
                filtered_history["merchant_category"].dropna().unique().tolist()
            ),

        )

        payment_filter = st.selectbox(

            "Payment Method",

            ["All"] + sorted(
                filtered_history["payment_method"].dropna().unique().tolist()
            ),

        )

    # --------------------------------------------------------
    # Apply Filters
    # --------------------------------------------------------

    if risk_filter != "All":

        filtered_history = filtered_history[
            filtered_history["risk"] == risk_filter
        ]

    if city_filter != "All":

        filtered_history = filtered_history[
            filtered_history["city"] == city_filter
        ]

    if merchant_filter != "All":

        filtered_history = filtered_history[
            filtered_history["merchant_category"] == merchant_filter
        ]

    if payment_filter != "All":

        filtered_history = filtered_history[
            filtered_history["payment_method"] == payment_filter
        ]

st.write("")
st.write("")
# ============================================================
# PART 4
# Search Results
# ============================================================

st.subheader("📋 Search Results")

if filtered_history.empty:

    st.warning("No matching transactions found.")

else:

    display_columns = [

        "timestamp",

        "amount",

        "city",

        "merchant_category",

        "payment_method",

        "device",

        "risk",

        "prob_fraud",

        "prob_legit",

    ]

    available_columns = [

        column

        for column in display_columns

        if column in filtered_history.columns

    ]

    results = filtered_history[available_columns].copy()

    results = results.rename(

        columns={

            "timestamp": "Timestamp",

            "amount": "Amount (₹)",

            "city": "City",

            "merchant_category": "Merchant",

            "payment_method": "Payment",

            "device": "Device",

            "risk": "Prediction",

            "prob_fraud": "Fraud Probability",

            "prob_legit": "Legitimate Probability",

        }

    )

    # Show newest records first
    results = results.iloc[::-1]

    st.dataframe(

        results,

        width="stretch",

        hide_index=True,

    )

st.write("")
st.write("")
# ============================================================
# PART 5
# Search Statistics
# ============================================================

st.subheader("📊 Search Statistics")

if filtered_history.empty:

    st.info("No statistics available.")

else:

    total_results = len(filtered_history)

    fraud_results = len(
        filtered_history[
            filtered_history["risk"] == "Fraud"
        ]
    )

    suspicious_results = len(
        filtered_history[
            filtered_history["risk"] == "Suspicious"
        ]
    )

    legitimate_results = len(
        filtered_history[
            filtered_history["risk"] == "Legitimate"
        ]
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "Results Found",
            total_results,
        )

    with col2:

        st.metric(
            "Fraud",
            fraud_results,
        )

    with col3:

        st.metric(
            "Suspicious",
            suspicious_results,
        )

    with col4:

        st.metric(
            "Legitimate",
            legitimate_results,
        )

st.write("")
st.write("")
# ============================================================
# PART 8
# Transaction Inspector
# ============================================================

st.write("")
st.write("")

st.subheader("🔎 Transaction Inspector")

if filtered_history.empty:

    st.info("No transactions available.")

else:

    inspector = filtered_history.iloc[::-1].copy()

    inspector["Transaction"] = inspector.apply(
        lambda r: (
            f"{r['timestamp']} | "
            f"₹{float(r['amount']):,.0f} | "
            f"{r['city']} | "
            f"{r['risk']}"
        ),
        axis=1,
    )

    selected = st.selectbox(
        "Select a transaction",
        inspector["Transaction"],
    )

    tx = inspector[
        inspector["Transaction"] == selected
    ].iloc[0]

    left, right = st.columns(2)

    with left:

        st.markdown("### Transaction Details")

        st.write("**Timestamp:**", tx["timestamp"])
        st.write("**Amount:** ₹{:,.2f}".format(float(tx["amount"])))
        st.write("**City:**", tx["city"])
        st.write("**Merchant:**", tx["merchant_category"])
        st.write("**Payment Method:**", tx["payment_method"])
        st.write("**Device:**", tx["device"])

    with right:

        st.markdown("### Prediction")

        st.metric("Risk", tx["risk"])

        st.progress(float(tx["prob_fraud"]))
        st.write(f"Fraud Probability : {tx['prob_fraud']:.2%}")

        st.progress(float(tx["prob_legit"]))
        st.write(f"Legitimate Probability : {tx['prob_legit']:.2%}")

        if tx["risk"] == "Fraud":
            st.error("🚨 High Risk Transaction")

        elif tx["risk"] == "Suspicious":
            st.warning("⚠ Manual Review Recommended")

        else:
            st.success("✅ Safe Transaction")
# ============================================================
# PART 9
# Search Insights
# ============================================================

st.write("")
st.write("")

st.subheader("📈 Search Insights")

if filtered_history.empty:

    st.info("No insights available.")

else:

    left, right = st.columns(2)

    # --------------------------------------------------------
    # Top Risky Cities
    # --------------------------------------------------------

    with left:

        st.markdown("### 🏙️ Top Risky Cities")

        city_counts = (
            filtered_history
            .groupby("city")
            .size()
            .reset_index(name="Transactions")
            .sort_values(
                "Transactions",
                ascending=False,
            )
            .head(10)
        )

        st.bar_chart(
            city_counts.set_index("city")
        )

    # --------------------------------------------------------
    # Merchant Category Distribution
    # --------------------------------------------------------

    with right:

        st.markdown("### 🛒 Merchant Categories")

        merchant_counts = (
            filtered_history
            .groupby("merchant_category")
            .size()
            .reset_index(name="Transactions")
            .sort_values(
                "Transactions",
                ascending=False,
            )
            .head(10)
        )

        st.bar_chart(
            merchant_counts.set_index("merchant_category")
        )

st.write("")

# ============================================================
# Risk Score Analysis
# ============================================================

if (
    not filtered_history.empty
    and "prob_fraud" in filtered_history.columns
):

    st.markdown("### 📉 Fraud Probability Distribution")

    probability = (
        filtered_history["prob_fraud"] * 100
    )

    st.line_chart(probability)

st.write("")

# ============================================================
# Quick Investigation Summary
# ============================================================

if not filtered_history.empty:

    highest = filtered_history.loc[
        filtered_history["prob_fraud"].idxmax()
    ]

    st.info(
        f"""
### 🚨 Highest Risk Transaction

**Fraud Probability:** {highest['prob_fraud']:.2%}

**City:** {highest['city']}

**Merchant:** {highest['merchant_category']}

**Payment Method:** {highest['payment_method']}

**Prediction:** {highest['risk']}
"""
    )

# ============================================================
# PART 6
# Export Search Results
# ============================================================

st.subheader("📥 Export Search Results")

if filtered_history.empty:

    st.info("No search results available for export.")

else:

    csv_data = filtered_history.to_csv(
        index=False
    ).encode("utf-8")

    st.download_button(

        label="⬇️ Download Filtered Results (CSV)",

        data=csv_data,

        file_name="PayGuard_Search_Results.csv",

        mime="text/csv",

        width="stretch",

    )

st.write("")
st.write("")
# ============================================================
# PART 7
# Search Information
# ============================================================

st.subheader("ℹ️ Search Information")

if filtered_history.empty:

    st.warning("No matching transactions found.")

else:

    col1, col2 = st.columns(2)

    with col1:

        st.metric(

            "Filtered Records",

            len(filtered_history),

        )

    with col2:

        if "timestamp" in filtered_history.columns:

            latest_time = filtered_history.iloc[-1]["timestamp"]

            st.metric(

                "Latest Matching Transaction",

                latest_time,

            )

        else:

            st.metric(

                "Latest Matching Transaction",

                "N/A",

            )

st.write("")
st.divider()

st.caption(
    "© 2026 PayGuard AI • Transaction Search & Investigation"
)